sudo: false
language: go
go:
- 1.6.2
install:
- go get -u github.com/kardianos/govendor
- govendor sync
script: go test ./...
deploy:
  provider: heroku
  app:
    master: snap-plugin-webapi-staging
    production: snap-plugin-webapi
  api_key:
    secure: Wptq6dGx7yNjSOdcKqvj8q0pEImC4pOVzaBUTuazSuIk+F8/RHGNpvDG5759X9YjsJAPczN3NffsnYRCa6aWX0Iqp2JPKTMf1QcXA5/UnZbBQefczgWKuGT9fcR7E3lrCE83/AfWPOrzI+KkXSQw4+d05lVMju9o9Q8Xo367U9V5w9Y8s3Bjmmddb77U4VfGbcmjhB3B+XoJcHifmTWdrim2ODdPgOKNffedPm0rBFqIILDIWpnR+QJAiLz+EoufVzC/mpu/TyI0x9bV5ICqEtwewp+CQxgWIVPg//al5ksDZlGUZ9aM2ssQoT7JftZ35PDN0krOKz0pwDIEJuvJqNLK7KLg63mq+VFQ+TSsb4j7scCHqPMT/ERAQ/1D5rtK5LjzwKwqHUh8Ste7Xb2zLmlKER8GCW/urdQ3Ju6JHLOhG9IVf4mYeQLQUvM5RNd0nUhPVsE6vQwqTlGsE6+LWDzGFxKozjdX2k28vCyHzqItu2KxCG4fTJt08IQ5Dx2MZbwResD9DiVYXFR1EL+A0hVAFoVG0eKn2NYIF4fnz6/0ZzAeSrAPcjfwbRpuvXsU2X3viWIAFiXLhIq6igvItn6RAx6GS7ydCfn984I8zH9IwmfzAYVNubnJWuYB48D8TIq9GJGlpucwdwGr4BM6q7SwtgEt0DkpD02dRsEsi3s=
notifications:
  email: false
  slack:
    secure: ELKEJX9SmlQl/GJM4Azd+KscDyIWYKMFC8hL+Ym38Xu4PWI/z38n7gnhlMrvHbk8CUEfyOu0Tv1TG+u2dH2t9Se39bIg8CJm32B7sG36f3h0uraSK2IMcR3x/58dXihU0I32AANvqv6aweDpO8LVKoTP8h8vIDfvIXBn82vUd+JZha6IeyfpsXXPJ019HjOXaxIU3+DNrnQ28NDLEfZvvAx20kb+WvllUXpCYPyCyMJ0AsW6hFTVeFChy/Fu8mVyZqPMRVilUZcfvTHDLQ91Aa0uMlaaelEq1g0qJ4bRObH73NU7iWQJMzz52jbdm9XSAHEPeU2B8ubmUQckhsGaIBC6qK4mg8mhPDcO1aYop5bZea6eMijgUlfHNyG8LsJedtTs5g+CLm0r99b4QYywt4jHqag/P7sbwS0K/yE5tcRjwJfWdbtx3womMRuAUoL0oqL5l74cTJ9PqvaMguZlo+fbHdFNW+ixeIjQZDwzycub8rgHhQPbM2cVTvDBgliHZKBcy45fpl9donA1OrVSrG3mR+9OlH4mhenDfjXjqlDL3umEuMT3nMySf4SEGHQXBJaEHiI8L/kMQ8HTpVCaSyvcfzzhHgdJ8SATRVOV+YWK4dV+LjAbCCdpIomI4Qd0Fz+JIMGap45Kk8u/ItxYhgsfbuSqTIS6Y8qIS8OhNm8=
